[package]
name = "rand-ip"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ipnet = "2.5.0"
iprange = "0.6.7"
rand = "0.8.5"
regex = { version = "1.1.8", features = ["pattern"] } 
